on:
  push:
    branches:
      - 259-add-link-checker-to-ci # todo - remove after testing
      # - '*' # todo - make sure this isn't commented out when done testing
      # - '!master' # todo - make sure this isn't commented out when done testing
name: Build Any Branch
jobs:
  BuildAnyBranch:
    name:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch the Docsy theme
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - name: Install Node depencies
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm install -g postcss-cli
      - run: npm i -D autoprefixer

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.71.1"
          extended: true

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14' # Pinning to current version as of Aug 3, 2020 for stability

      - name: Install Muffet
        run: go get -u github.com/raviqqe/muffet

#      - name: Serve Hugo site
#      - run: hugo server
#      - run: sleep 5 # taken from another muffet CI recipe - this makes sure hugo is full spun up and ready
#
#      - name: Run Muffet link checkier
#        run: |
#          muffet http://localhost:1313\
#          --ignore-fragments \
#          -exclude ".*github\.com.*|.*demo\.app\.medicmobile\.org.*|.*download\.docker\.com.*|" \
#          -exclude ".*www\.npmjs\.com/org/medic/team/developers.*|.*github\.com/medic/cht-docs/issues/new.*|.*localhost:5984.*" \

      # todo - remove this comment:
      # muffet -f  -e ".*github\.com.*" -e  ".*demo\.app\.medicmobile\.org.*"  -e  ".*download\.docker\.com.*" -e ".*www\.npmjs\.com/org/medic/team/developers.*" -e ".*github\.com/medic/cht-docs/issues/new.*" -e ".*localhost:5984.*"  http://localhost:1313

      # is this needed now that we build above when running `hugo server`?
      - name: Build
        run: hugo
