name: CHT Documentation Site Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.71.1"
          extended: true

      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPOLY_TO_SITE}}
          external_repository: medic/medic.github.io
          publish_dir: ./public
          user_name: nomulex
          user_email: nomulex@gmail.com
          publish_branch: beta